site_name: Treinamento Kubernetes Operators com Go
site_description: Treinamento self-paced para desenvolvimento de Operators Kubernetes com Go
site_author: Fabrizio Malta Di Napoli
repo_url: https://github.com/fmnapoli/kubernetes-operators-training

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - content.code.copy
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
  - search
  - mermaid2

nav:
  - Início: index.md
  - Dia 0 - Setup:
    - Introdução: dia0/01-introducao.md
    - Instalação Manual: dia0/02-instalacao-manual.md
    - Script de Automação: dia0/03-script-automacao.md
    - Validação: dia0/04-validacao.md
  - Dia 1 - Fundamentos:
    - Introdução: dia1/01-introducao.md
    - API Kubernetes: dia1/02-api-kubernetes.md
    - Prática: dia1/03-pratica.md